field: ab14d0d5-64c5-4aa4-a0a9-eba30e6f8e87 # Blocks
fieldLayouts:
  b7a8df53-8a6a-43f5-ab0d-1001b87c9d41:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: d307767d-4f9c-4516-9aa8-168eb852cdaa # Image
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 637a334d-9dfd-4432-9eaf-d11d4eab2efc
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 89537844-a891-479c-87a1-99408651d29f
        userCondition: null
fields:
  d307767d-4f9c-4516-9aa8-168eb852cdaa: # Image
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: image
    instructions: null
    name: Image
    searchable: false
    settings:
      allowSelfRelations: false
      allowSubfolders: false
      allowUploads: true
      allowedKinds:
        - image
      branchLimit: null
      defaultUploadLocationSource: 'volume:b2f38830-4aed-452f-a5c0-c94f0483066b' # Images
      defaultUploadLocationSubpath: null
      localizeRelations: false
      maintainHierarchy: false
      maxRelations: 1
      minRelations: null
      previewMode: full
      restrictFiles: true
      restrictLocation: false
      restrictedDefaultUploadSubpath: null
      restrictedLocationSource: 'volume:b2f38830-4aed-452f-a5c0-c94f0483066b' # Images
      restrictedLocationSubpath: null
      selectionLabel: null
      showSiteMenu: false
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      sources:
        - 'volume:b2f38830-4aed-452f-a5c0-c94f0483066b' # Images
      targetSiteId: null
      validateRelatedElements: false
      viewMode: large
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
handle: image
name: Image
sortOrder: 2
