field: ab14d0d5-64c5-4aa4-a0a9-eba30e6f8e87 # Blocks
fieldLayouts:
  6ecbc535-fba1-44dd-94d7-960e019e5f8c:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 4a225389-8e62-4cf2-a2a4-98db6a7f36c1 # Text
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8bda5edc-214f-4b98-a4dc-84136b38a32b
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: d65d4e83-672d-4a55-97a7-32f2f16540ef
        userCondition: null
fields:
  4a225389-8e62-4cf2-a2a4-98db6a7f36c1: # Text
    columnSuffix: peybavnd
    contentColumnType: text
    fieldGroup: null
    handle: text
    instructions: null
    name: Text
    searchable: false
    settings:
      availableTransforms: ''
      availableVolumes: '*'
      ckeConfig: 6bcf800f-abaf-4d08-8d13-e5f062f5be41 # Full
      columnType: text
      defaultTransform: null
      enableSourceEditingForNonAdmins: false
      purifierConfig: null
      purifyHtml: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      showWordCount: false
      wordLimit: null
    translationKeyFormat: null
    translationMethod: none
    type: craft\ckeditor\Field
handle: richText
name: 'Rich Text'
sortOrder: 1
