fieldLayouts:
  63463221-2571-43db-8fd3-5d1ef69c97a4:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: e85445ba-5d4b-419d-a6e2-689d900457e3
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: ab14d0d5-64c5-4aa4-a0a9-eba30e6f8e87 # Blocks
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9d9c53e2-44c6-46cd-a2e4-3982f86318c3
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: edf7cfef-f6ec-41ac-b483-c93d2b1bbdda
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: e26ae72c-1e23-475b-8cbe-20e01eee8649 # SEO
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2447dd24-186d-4bf1-9b27-4fa5a8a21e60
            userCondition: null
            warning: null
            width: 100
        name: SEO
        uid: 262a0692-1236-4fc3-8dc0-966df95489e4
        userCondition: null
handle: default
hasTitleField: true
name: Default
section: 895e2e68-6054-4354-a6a8-b457ec60b48e # Pages
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
