columnSuffix: null
contentColumnType: string
fieldGroup: 03c95542-ae23-47da-b13d-e2c3a9f1c098 # Common
handle: blocks
instructions: null
name: Blocks
searchable: false
settings:
  contentTable: '{{%matrixcontent_blocks}}'
  maxBlocks: null
  minBlocks: null
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
