columnSuffix: null
handle: richText
instructions: null
name: 'Rich Text'
searchable: true
settings:
  availableTransforms: ''
  availableVolumes: '*'
  defaultTransform: null
  headingLevels:
    - 2
    - 3
    - 4
  purifierConfig: null
  purifyHtml: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  showWordCount: false
  toolbar:
    - heading
    - '|'
    - bold
    - italic
    - link
  wordLimit: null
translationKeyFormat: null
translationMethod: none
type: craft\ckeditor\Field
