defaultPlacement: end
enableVersioning: true
handle: pages
name: Pages
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  a1a8f47d-bc64-4e83-b84b-951a11df4a8e: # $PRIMARY_SITE_NAME
    enabledByDefault: true
    hasUrls: true
    template: pages/_entry
    uriFormat: '{parent.uri}/{slug}'
structure:
  maxLevels: null
  uid: f6d8a675-03fa-44d4-8fef-68b4cef10013
type: structure
